# Generated by Django 3.1.14 on 2025-01-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_pokemonentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='Lan',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='Lon',
            field=models.FloatField(),
        ),
    ]
