# Generated by Django 3.1.14 on 2025-02-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0007_auto_20250204_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='Defence',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='Health',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='Level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='Stamina',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='Strength',
            field=models.IntegerField(null=True),
        ),
    ]
