# Generated by Django 3.1.14 on 2025-02-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0011_auto_20250204_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='img',
            field=models.ImageField(null=True, upload_to='pokemon_images'),
        ),
    ]
