# Generated by Django 3.1.14 on 2025-02-05 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0012_auto_20250205_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='Lan',
            new_name='Lat',
        ),
    ]
