# Generated by Django 3.1.14 on 2025-02-21 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0020_auto_20250221_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Entities', to='pokemon_entities.pokemon', verbose_name='Вид покемона:'),
        ),
    ]
