# Generated by Django 3.1.14 on 2025-02-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0025_auto_20250221_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='defence',
            field=models.PositiveBigIntegerField(blank=True, default=0, verbose_name='Защита покемона:'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='health',
            field=models.PositiveBigIntegerField(blank=True, default=0, verbose_name='Здоровье покемона:'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='level',
            field=models.PositiveBigIntegerField(blank=True, default=0, verbose_name='Уровень покемона:'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='stamina',
            field=models.PositiveBigIntegerField(blank=True, default=0, verbose_name='Выносливость покемона:'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='strength',
            field=models.PositiveBigIntegerField(blank=True, default=0, verbose_name='Сила покемона:'),
        ),
    ]
